name: Categorize Starred Repositories (ACLI Rovo Dev)

on:
  schedule:
    # Läuft jeden Tag um 03:00 UTC (eine Stunde nach der OpenAI Version)
    - cron: '0 3 * * *'
  workflow_dispatch:
    # Ermöglicht manuelles Ausführen

jobs:
  categorize-repos:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Dependencies
      run: |
        pip install requests PyGithub python-dotenv
    
    - name: Install Atlassian CLI (ACLI)
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg2
        sudo mkdir -p -m 755 /etc/apt/keyrings
        wget -nv -O- https://acli.atlassian.com/gpg/public-key.asc | sudo gpg --dearmor -o /etc/apt/keyrings/acli-archive-keyring.gpg
        sudo chmod go+r /etc/apt/keyrings/acli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/acli-archive-keyring.gpg] https://acli.atlassian.com/linux/deb stable main" | sudo tee /etc/apt/sources.list.d/acli.list > /dev/null
        sudo apt update
        sudo apt install -y acli
    
    - name: Fetch and Categorize Starred Repos with ACLI Rovo Dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.repository_owner }}
        ATLASSIAN_EMAIL: ${{ secrets.ATLASSIAN_EMAIL }}
        ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}
      run: python scripts/categorize_starred_repos_rovo.py
    
    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-categorize starred repositories with ACLI Rovo Dev $(date +%Y-%m-%d)"
          git push
        fi